INSERT INTO artist (PhotosURL, name, Description, genre, Year, Country)
VALUES
-- US Artists
('/assets/taylor_swift.jpg', 'Taylor Swift', 'Global pop icon known for storytelling in her music.', 'Pop', '2006', 'USA'),
('/assets/beyonce.jpg', 'Beyoncé', 'Award-winning singer and performer known for her powerful voice and stage presence.', 'R&B', '2003', 'USA'),
('/assets/eminem.jpg', 'Eminem', 'One of the best-selling artists in hip-hop history.', 'Hip-hop', '1999', 'USA'),
('/assets/bruce_springsteen.jpg', 'Bruce Springsteen', 'Rock legend known as "The Boss."', 'Rock', '1973', 'USA'),
('/assets/lady_gaga.jpg', 'Lady Gaga', 'Pop artist known for her unique style and powerful anthems.', 'Pop', '2008', 'USA'),
('/assets/billie_eilish.jpg', 'Billie Eilish', 'Pop sensation known for her unique sound and style.', 'Pop', '2015', 'USA'),
('/assets/frank_sinatra.jpg', 'Frank Sinatra', 'Iconic singer and actor.', 'Jazz', '1939', 'USA'),
('/assets/michael_jackson.jpg', 'Michael Jackson', 'The King of Pop.', 'Pop', '1964', 'USA'),
('/assets/madonna.jpg', 'Madonna', 'Pop icon known for her boundary-pushing music.', 'Pop', '1983', 'USA'),
('/assets/prince.jpg', 'Prince', 'Musical innovator and pop legend.', 'Pop/Rock', '1978', 'USA'),

-- UK Artists
('/assets/adele.jpg', 'Adele', 'Grammy-winning artist known for her deep and emotional voice.', 'Pop', '2008', 'GBR'),
('/assets/ed_sheeran.jpg', 'Ed Sheeran', 'Singer-songwriter with numerous chart-topping hits.', 'Pop', '2011', 'GBR'),
('/assets/elton_john.jpg', 'Elton John', 'Iconic pianist and singer with a career spanning decades.', 'Rock', '1970', 'GBR'),
('/assets/amy_winehouse.jpg', 'Amy Winehouse', 'Jazz and soul singer known for her distinct voice.', 'Soul', '2003', 'GBR'),
('/assets/dua_lipa.jpg', 'Dua Lipa', 'Pop star with an array of global hits.', 'Pop', '2017', 'GBR'),
('/assets/freddie_mercury.jpg', 'Freddie Mercury', 'Legendary Queen frontman.', 'Rock', '1973', 'GBR'),
('/assets/david_bowie.jpg', 'David Bowie', 'Visionary artist and pop culture icon.', 'Rock/Pop', '1967', 'GBR'),
('/assets/paul_mccartney.jpg', 'Paul McCartney', 'Beatles member and legendary songwriter.', 'Rock', '1960', 'GBR'),
('/assets/harry_styles.jpg', 'Harry Styles', 'Pop artist and former One Direction member.', 'Pop', '2017', 'GBR'),
('/assets/george_michael.jpg', 'George Michael', 'Pop icon with a legacy of hits.', 'Pop', '1981', 'GBR'),

-- European Artists
('/assets/andrea_bocelli.jpg', 'Andrea Bocelli', 'Italian tenor with a global following.', 'Opera', '1994', 'ITA'),
('/assets/david_guetta.jpg', 'David Guetta', 'French DJ and music producer.', 'Electronic', '2002', 'FRA'),
('/assets/enrique_iglesias.jpg', 'Enrique Iglesias', 'Spanish pop star and performer.', 'Pop', '1995', 'ESP'),
('/assets/abba.jpg', 'ABBA', 'Swedish pop group with a legacy of hits.', 'Pop', '1972', 'SWE'),
('/assets/roxette.jpg', 'Roxette', 'Swedish duo known for their catchy pop-rock songs.', 'Pop-rock', '1986', 'SWE'),

-- Chinese Artists
('/assets/jay_chou.jpg', 'Jay Chou', 'Mandopop king and musical innovator.', 'Mandopop', '2000', 'CHN'),
('/assets/faye_wong.jpg', 'Faye Wong', 'Canto-pop legend and actress.', 'C-pop', '1989', 'CHN'),
('/assets/lang_lang.jpg', 'Lang Lang', 'World-renowned classical pianist.', 'Classical', '1995', 'CHN'),
('/assets/gem.jpg', 'G.E.M.', 'Singer-songwriter with a powerful voice.', 'Pop', '2008', 'CHN'),
('/assets/li_yuchun.jpg', 'Li Yuchun', 'Pop star and cultural icon.', 'Pop', '2005', 'CHN'),

-- Japanese Artists
('/assets/utada_hikaru.jpg', 'Utada Hikaru', 'Singer-songwriter known for her emotional music.', 'J-pop', '1998', 'JPN'),
('/assets/namie_amuro.jpg', 'Namie Amuro', 'Pop and R&B legend in Japan.', 'Pop', '1995', 'JPN'),
('/assets/babymetal.jpg', 'Babymetal', 'Innovative metal band blending J-pop and heavy metal.', 'Metal', '2010', 'JPN'),
('/assets/yuji_ohno.jpg', 'Yuji Ohno', 'Jazz composer and pianist.', 'Jazz', '1978', 'JPN'),
('/assets/arashi.jpg', 'Arashi', 'Popular boy band with a dedicated fanbase.', 'J-pop', '1999', 'JPN'),

-- Korean Artists
('/assets/bts.jpg', 'BTS', 'Global K-pop phenomenon.', 'K-pop', '2013', 'KOR'),
('/assets/blackpink.jpg', 'BLACKPINK', 'One of the biggest K-pop girl groups.', 'K-pop', '2016', 'KOR'),
('/assets/psy.jpg', 'PSY', 'Pop artist famous for "Gangnam Style."', 'K-pop', '2001', 'KOR'),
('/assets/iu.jpg', 'IU', 'Singer-songwriter known for her versatility.', 'Pop', '2008', 'KOR'),
('/assets/taeyeon.jpg', 'Taeyeon', 'Lead singer of Girls’ Generation and solo artist.', 'Pop', '2007', 'KOR'),

-- Indonesian Artists
('/assets/agnez_mo.jpg', 'Agnez Mo', 'International pop star from Indonesia.', 'Pop', '2003', 'IDN'),
('/assets/rhoma_irama.jpg', 'Rhoma Irama', 'King of Dangdut.', 'Dangdut', '1970', 'IDN'),
('/assets/tulus.jpg', 'Tulus', 'Indie-pop singer-songwriter.', 'Indie-pop', '2011', 'IDN'),
('/assets/raisa.jpg', 'Raisa', 'Pop singer with a strong fanbase.', 'Pop', '2011', 'IDN'),
('/assets/nidji.jpg', 'Nidji', 'Rock band with numerous hits.', 'Rock', '2002', 'IDN'),

-- Hispanic Artists
('/assets/shakira.jpg', 'Shakira', 'Global superstar blending Latin and pop music.', 'Pop', '1990', 'COL'),
('/assets/luis_miguel.jpg', 'Luis Miguel', 'Mexican icon with an illustrious career.', 'Ballad', '1982', 'MEX'),
('/assets/jennifer_lopez.jpg', 'Jennifer Lopez', 'Singer and actress with a string of hits.', 'Pop', '1999', 'USA'),
('/assets/rosalia.jpg', 'Rosalía', 'Spanish artist blending flamenco and modern sounds.', 'Flamenco-pop', '2017', 'ESP'),
('/assets/ricky_martin.jpg', 'Ricky Martin', 'Pop sensation and Latin music icon.', 'Pop', '1991', 'PRI'),

-- Spanish Artists
('/assets/julio_iglesias.jpg', 'Julio Iglesias', 'Legendary Spanish singer.', 'Ballad', '1968', 'ESP'),
('/assets/paco_de_lucia.jpg', 'Paco de Lucía', 'Revolutionary flamenco guitarist.', 'Flamenco', '1967', 'ESP'),
('/assets/alejandro_sanz.jpg', 'Alejandro Sanz', 'Renowned Spanish singer-songwriter.', 'Pop', '1991', 'ESP'),
('/assets/david_bisbal.jpg', 'David Bisbal', 'Pop artist with a powerful voice.', 'Pop', '2002', 'ESP'),
('/assets/joaquin_sabina.jpg', 'Joaquín Sabina', 'Singer-songwriter known for poetic lyrics.', 'Folk-rock', '1978', 'ESP');


INSERT INTO countries (country_code, country_name) VALUES
('AFG', 'Afghanistan'),
('ALB', 'Albania'),
('DZA', 'Algeria'),
('AND', 'Andorra'),
('AGO', 'Angola'),
('ATG', 'Antigua and Barbuda'),
('ARG', 'Argentina'),
('ARM', 'Armenia'),
('AUS', 'Australia'),
('AUT', 'Austria'),
('AZE', 'Azerbaijan'),
('BHS', 'Bahamas'),
('BHR', 'Bahrain'),
('BGD', 'Bangladesh'),
('BRB', 'Barbados'),
('BLR', 'Belarus'),
('BEL', 'Belgium'),
('BLZ', 'Belize'),
('BEN', 'Benin'),
('BHU', 'Bhutan'),
('BOL', 'Bolivia'),
('BIH', 'Bosnia and Herzegovina'),
('BWA', 'Botswana'),
('BRA', 'Brazil'),
('BRN', 'Brunei'),
('BGR', 'Bulgaria'),
('BFA', 'Burkina Faso'),
('BDI', 'Burundi'),
('CPV', 'Cabo Verde'),
('KHM', 'Cambodia'),
('CMR', 'Cameroon'),
('CAN', 'Canada'),
('CAF', 'Central African Republic'),
('TCD', 'Chad'),
('CHL', 'Chile'),
('CHN', 'China'),
('COL', 'Colombia'),
('COM', 'Comoros'),
('COG', 'Congo'),
('COD', 'Democratic Republic of the Congo'),
('CRI', 'Costa Rica'),
('CIV', 'Ivory Coast'),
('HRV', 'Croatia'),
('CUB', 'Cuba'),
('CYP', 'Cyprus'),
('CZE', 'Czech Republic'),
('DNK', 'Denmark'),
('DJI', 'Djibouti'),
('DMA', 'Dominica'),
('DOM', 'Dominican Republic'),
('ECU', 'Ecuador'),
('EGY', 'Egypt'),
('SLV', 'El Salvador'),
('GNQ', 'Equatorial Guinea'),
('ERI', 'Eritrea'),
('EST', 'Estonia'),
('ETH', 'Ethiopia'),
('FJI', 'Fiji'),
('FIN', 'Finland'),
('FRA', 'France'),
('GAB', 'Gabon'),
('GMB', 'Gambia'),
('GEO', 'Georgia'),
('DEU', 'Germany'),
('GHA', 'Ghana'),
('GRC', 'Greece'),
('GRD', 'Grenada'),
('GTM', 'Guatemala'),
('GIN', 'Guinea'),
('GNB', 'Guinea-Bissau'),
('GUY', 'Guyana'),
('HTI', 'Haiti'),
('HND', 'Honduras'),
('HUN', 'Hungary'),
('ISL', 'Iceland'),
('IND', 'India'),
('IDN', 'Indonesia'),
('IRN', 'Iran'),
('IRQ', 'Iraq'),
('IRL', 'Ireland'),
('ISR', 'Israel'),
('ITA', 'Italy'),
('JAM', 'Jamaica'),
('JPN', 'Japan'),
('JOR', 'Jordan'),
('KAZ', 'Kazakhstan'),
('KEN', 'Kenya'),
('KIR', 'Kiribati'),
('KOR', 'South Korea'),
('KWT', 'Kuwait'),
('KGZ', 'Kyrgyzstan'),
('LAO', 'Laos'),
('LVA', 'Latvia'),
('LBN', 'Lebanon'),
('LSO', 'Lesotho'),
('LBR', 'Liberia'),
('LBY', 'Libya'),
('LIE', 'Liechtenstein'),
('LTU', 'Lithuania'),
('LUX', 'Luxembourg'),
('MDG', 'Madagascar'),
('MWI', 'Malawi'),
('MYS', 'Malaysia'),
('MDV', 'Maldives'),
('MLI', 'Mali'),
('MLT', 'Malta'),
('MHL', 'Marshall Islands'),
('MRT', 'Mauritania'),
('MUS', 'Mauritius'),
('MEX', 'Mexico'),
('FSM', 'Micronesia'),
('MDA', 'Moldova'),
('MON', 'Monaco'),
('MNG', 'Mongolia'),
('MNE', 'Montenegro'),
('MAR', 'Morocco'),
('MOZ', 'Mozambique'),
('MMR', 'Myanmar'),
('NAM', 'Namibia'),
('NRU', 'Nauru'),
('NPL', 'Nepal'),
('NLD', 'Netherlands'),
('NZL', 'New Zealand'),
('NIC', 'Nicaragua'),
('NER', 'Niger'),
('NGA', 'Nigeria'),
('PRK', 'North Korea'),
('MKD', 'North Macedonia'),
('NOR', 'Norway'),
('OMN', 'Oman'),
('PAK', 'Pakistan'),
('PLW', 'Palau'),
('PAN', 'Panama'),
('PNG', 'Papua New Guinea'),
('PRY', 'Paraguay'),
('PER', 'Peru'),
('PHL', 'Philippines'),
('POL', 'Poland'),
('PRT', 'Portugal'),
('PRI', 'Puerto Rico'),
('QAT', 'Qatar'),
('ROU', 'Romania'),
('RUS', 'Russia'),
('RWA', 'Rwanda'),
('STP', 'São Tomé and Príncipe'),
('SAU', 'Saudi Arabia'),
('SEN', 'Senegal'),
('SRB', 'Serbia'),
('SYC', 'Seychelles'),
('SLE', 'Sierra Leone'),
('SGP', 'Singapore'),
('SVK', 'Slovakia'),
('SVN', 'Slovenia'),
('SLB', 'Solomon Islands'),
('SOM', 'Somalia'),
('ZAF', 'South Africa'),
('ESP', 'Spain'),
('LKA', 'Sri Lanka'),
('SDN', 'Sudan'),
('SUR', 'Suriname'),
('SWE', 'Sweden'),
('CHE', 'Switzerland'),
('SYR', 'Syria'),
('TWN', 'Taiwan'),
('TJK', 'Tajikistan'),
('TZA', 'Tanzania'),
('THA', 'Thailand'),
('TGO', 'Togo'),
('TON', 'Tonga'),
('TTO', 'Trinidad and Tobago'),
('TUN', 'Tunisia'),
('TUR', 'Turkey'),
('TKM', 'Turkmenistan'),
('TUV', 'Tuvalu'),
('UGA', 'Uganda'),
('UKR', 'Ukraine'),
('ARE', 'United Arab Emirates'),
('GBR', 'United Kingdom'),
('USA', 'United States'),
('URY', 'Uruguay'),
('UZB', 'Uzbekistan'),
('VUT', 'Vanuatu'),
('VEN', 'Venezuela'),
('VNM', 'Vietnam'),
('YEM', 'Yemen'),
('ZMB', 'Zambia'),
('ZWE', 'Zimbabwe');

--Run psql tool buat import csv atau bisa di import dari klik kanan tabel di pgadmin
\copy public.venue (id, name, address, address2, city, state, zip, geocodable, latitude, longitude, website, phone, email)
FROM 'C:\Users\Lenovo\OneDrive - Universitas Katolik Parahyangan\Drive Kuliah\Pemrograman Berbasis Web\Tubes\TubesPBW\sql\venues.csv'
DELIMITER ','
CSV HEADER
NULL AS '';

