--INSERT SHOW
INSERT INTO "show" (showName, date, description, idVenue) VALUES
    ('Enchanted Evening Festival', '2023-03-15', 'A magical night with unforgettable performances.', 1),
    ('Queen Bey Experience Festival', '2022-03-20', 'An electrifying event featuring incredible guest performers.', 2),
    ('Rap Revolution Festival', '2024-03-25', 'An evening of groundbreaking rap and raw emotion.', 3),
    ('Born to Rock Festival', '2020-04-01', 'A rock festival with legendary performances.', 4),
    ('Chromatic Dreams Festival', '2021-04-10', 'A night of avant-garde music and stunning visuals.', 5),
    ('Ocean Eyes Live Festival', '2024-04-18', 'An ethereal night of music and collaboration.', 6),
    ('Timeless Classics Festival', '2023-04-22', 'An evening of swing and jazz with timeless hits.', 7),
    ('King of Pop Tribute Festival', '2021-05-01', 'Celebrating iconic music with live performances.', 8),
    ('Vogue Night Festival', '2022-05-07', 'A dance-filled night featuring unforgettable acts.', 9),
    ('Purple Rain Experience Festival', '2020-05-15', 'A soulful journey through music with guest artists.', 10),
    ('Hello Again Festival', '2023-05-20', 'A heartfelt evening of powerful ballads.', 11),
    ('Strings of the Heart Festival', '2024-05-25', 'An acoustic evening with talented musicians.', 12),
    ('Rocketman Live Festival', '2022-06-01', 'A flamboyant festival experience with stellar performances.', 13),
    ('Back to Black Revival Festival', '2021-06-07', 'A soulful night celebrating timeless music.', 14),
    ('Future Nostalgia Tour Festival', '2020-06-12', 'A vibrant pop festival with unforgettable moments.', 15),
    ('Bohemian Nights Festival', '2023-06-20', 'A legendary rock night of iconic performances.', 16),
    ('Starman Tribute Festival', '2024-06-25', 'An artistic festival with stellar performances.', 17),
    ('Beatlemania Returns Festival', '2022-07-01', 'A nostalgic festival celebrating classic hits.', 18),
    ('Golden Hour Festival', '2020-07-05', 'A stylish music festival with unforgettable acts.', 19),
    ('Faith Forever Festival', '2021-07-10', 'A night celebrating timeless music and featured performers.', 20),
    ('Serenade of the Stars Festival', '2023-07-15', 'A classical music festival with breathtaking performances.', 21),
    ('Dance Fever Festival', '2024-07-20', 'An electrifying EDM festival with top-tier DJs.', 22),
    ('Bailando Nights Festival', '2022-07-25', 'A passionate Latin music festival with fiery performances.', 23),
    ('Dancing Queen Celebration Festival', '2021-07-30', 'A joyous festival night with chart-topping hits.', 24),
    ('Joyride Live Festival', '2020-08-01', 'A festival of nostalgia and unforgettable acts.', 25);
